### ISSUE TITLE
C1 data not registered in SPSS file

### ISSUE THREAD

**Issue by martinhed** [colmsjo/qualtrics#3]
(I have edited the following 14:30 Friday)

Most importantly: PressZero2 works fine in chrome, firefox and edge in that the numbers on the screen changes when I press the zero key (even on the first attempt). However, when I download the spss file, the donation is not registered. The variable is there (press_zero_data), but the value is either window.zeroCount:0;toPCF:0;toMe:18 (in proself condition) or window.zeroCount:0;toPCF:18;toMe:0 (in prosocial condition) regardless how many click I made. 

If you could fix this problem in PressZero2 I can hopefully integrate it in the same way in the new survey HT21_PILOT_4_CLOUD that I have now shared with you. If you could fix it in the new survey it would of course be even better. The block is called ”C1 semi strong default” and it occurs twice in the survey flow since it includes two conditions.

Less important (but desirable) would be if the donation choice could be registered (as embedded data?) under the variable name ”pengz”, since C1 in all other conditions are gathered in that variable (by means of embedded data). Also, it would be desirable if default condition could be registered (as embedded data?) under the variable name ”condition”, where proself default is 3 and prosocial condition is 4 (we will probably have nine conditions in total). As it is now, ”press_zero_data” and ”rand_prosocial” are string variables (I don’t know if it poses a problem that  ”pengz” and ”condition” are numeric). Anyway, if this is hard to fix it is not absolutely necessary – I can recode in SPSS afterwards.

Additionally, the wording needs to be slightly changed (in both conditions): change ”Winners will be drawn...” to ”Five winners will be drawn...”. 
If you find the time and energy for it, it would also be nice to make a few additional adjustments in order to replicate the other conditions as much as possible: no underlining of ”win an additional $18 lottery prize”, instead set that entire sentence in bold text. Also, please set Pediatric Cancer Foundation (PCF) in bold text (and keep the italics).

We hope to start data collection next week. Thanks!

**Comment by colmsjo** [comment]
I've created three new issues to make it easier to keep track of the work (enter a short comment on each to receive status updates).
