### ISSUE TITLE
C1 on page external to Qualtrics

### ISSUE THREAD

**Issue by martinhed** [colmsjo/qualtrics#7]
When I try the PressZero3-step1 (either as preview or using the distribution link) I do not get to any donation page - all I see is this:
<img width="774" alt="image" src="https://user-images.githubusercontent.com/93518602/140879544-e353b2a5-2922-462a-aead-ed9bf87aa9ef.png">
and when I click the forward button I see this:
<img width="772" alt="image" src="https://user-images.githubusercontent.com/93518602/140879735-ffe4813f-d43d-4d13-924b-cb0eaa981134.png">

When I try the PressZero3-step2 (either as preview or using the distribution link) all I see is this:
<img width="777" alt="image" src="https://user-images.githubusercontent.com/93518602/140880334-eee50d41-d37a-4058-a0ca-fcda155704b2.png">
and when I click the forward button I see this:
<img width="791" alt="image" src="https://user-images.githubusercontent.com/93518602/140880408-aed05b11-be34-4e1b-b8b5-feeb4207987d.png">

I have used safari and firefox

**Comment by colmsjo** [comment]
Press Link out ;-)

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by martinhed** [comment]
aha....
