### ISSUE TITLE
linking C1 from/to qualtrics

### ISSUE THREAD

**Issue by martinhed** [colmsjo/qualtrics#8]
It does not seem to be possible to have the next button link to the external page (only text in button changes). Perhaps, then, better to have a final page in the "shapes" part of the survey linking to the external page (we could disregard data from the first part altogether). The important question, then, is if there is a way to link the external C1 page to the final part of the qualtrics survey (which is in fact a separate survey). Could you do this?

**Comment by martinhed** [comment]
I have now shared three surveys with you: "HT21_PILOT_4_CLOUD - Copy" in which the survey flow will allow those who enter the conditions (there are two due to the fact that this category need to be doubly filled compared to the other conditions) "Semi-strong default 1" and "Semi-strong default 2" to exit the survey and automatically be directed to your zero-press page. I therefore need the url for your page. (Is there a problem that participants may be randomly assigned to the zero-press page simultaneously, given that there are two conditions and that they may spend some time deciding? I.e., is the page equipped to deal with more than one participants at the time?)
Once participants are finished on the press-zero page they should be directed to either "HT21_PILOT_4_Part2_Proself" (url: https://samgu.eu.qualtrics.com/jfe/form/SV_3ykeElPx20zls8K) or "HT21_PILOT_4_Part2_Prosocial" (url: https://samgu.eu.qualtrics.com/jfe/form/SV_23TFubG8uH0BDam), depending on which version of the zero-press page they got. Perhaps it is not necessary to have two different part 2 (depends on how the issue below is resolved):
Problem remains of linking press-zero individual data to the part 2 surveys. (It is not necessary to link press-zero data to the first part of the survey.) Is there a way? Possibly with the aid of ip-number, time stamp, etc?

**Comment by colmsjo** [comment]
I've done some modifications to make it easy to chain surveys and pass information from one survey to next. PressZero and RiceClick now work the same way. There are three parameters that are sent to these pages:
* s - the id of next survey (the external page will link back to this survey)
* c - the condition. PressZero will interpret 0 as PROSELF and any other number as PROSOCIAL. This parameter is sent back to next survey
* d - this can hold any data, for instance the participant id. This parameter is sent back to next survey.

There are now three surveys in Qualtrics that show how these pages can be used and linked. The d-parameter is used store the participantID from the first page and also the zero_count from the second page (separated with a comma). The third page will have all data that was collected this way.

There is no problem with multiple users.

/BR
Jonas

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by martinhed** [comment]
OK this seems great! However, I think I'm missing something. How are the participants supposed to get from one survey to another without clicking on the "link out" link? It does not seem possible to adjust the "next" button in that way, so it seems like they would need to click on the "link out" link, am I correct?

**Comment by colmsjo** [comment]
Change the End of survey section to redirct to the same URL as Link Out has. I've done this in SO-step1 and SO-step2 now.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by martinhed** [comment]
I have linked HT21_PILOT_4_Part1 via SO-step1 and SO-step2 to HT21_PILOT_4_Part2. Could you please check what I am doing wrong since the spss file obtained in HT21_PILOT_4_Part2 does not contain information from the donation page. Also, can I change the survey flow in SO-step1 and SO-step2 so that the "page" does not come up for the participants? (I.e., the page containing participantID:${e://Field/participantID} cond:${e://Field/cond} next_survey:${e://Field/next_survey} Link out)

This is immensely time consuming for me, trial-and-error over and over...

**Comment by colmsjo** [comment]
Wow thats one complex survey...I don't really understand what's going on but I noticed a few things:
1. Embedded data is set many times and also as the last step in the survey. I'd set participantID and cond at the top (and not change)
2. It seams as though you are using a randomizer together with cond? Not sure that makes any sense?
3. I don't see the fields c and d (and count if ClickZero will be used) in part2. These embedded fields should be declared at the top.

Keep in mind I'm not a Qualtrics expert but these are my thoughts...

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by martinhed** [comment]
Part 1 is not the one that will be used eventually, it has a restricted survey flow and I'm just trying to understand the logic, and see if things work, before I implement everything in the real survey. I think the crucial point is your number 3. So I need to add questions (named "participantID" and "cold") in Part2 in order for the data from PressZero to be inserted into the data file for Part 2? And how do I add the embedded fields c and d? In the survey flow? And should I copy exactly like they are in the surveys you created? This really is hard to understand, could you help?

**Comment by martinhed** [comment]
I have now added embedded fields in the beginning of the survey flow in Part2, as well as questions with the same names in Block 18. When I answer the survey, these variables still turn out empty. Could we have a brief chat about this on zoom, I think we are not communicating perfectly in this forum, perhaps I can better explain what I need and we can settle for some solution that is good enough

**Comment by colmsjo** [comment]
I'd start from something simpe that works (such as SO-step1/2/3) and build on that. Starting from something complex makes it very difficult to understand what's going on. I'll be in the office around 9:30, we can have a short Zoom chat then if that works for you.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by martinhed** [comment]
Hej Jonas, tack för mötet i morse. Jag tror att Patrik har löst det hela nu, det enda du behöver göra är att ändra så att din externa sida (PressZero-sidan) länkar till följande qualtrics-enkät: https://samgu.eu.qualtrics.com/jfe/form/SV_3ykeElPx20zls8K
Alla embedded data fungerar, så det är alltså bara själva "länk-delen" som behöver bytas ut. Jättefint om du har möjlighet att göra detta innan kl 3, annars när du hinner.

**Comment by colmsjo** [comment]
Antar att du menar den sida som PressZero ska länka tillbaka användaren till när hen trycker Next. Detta styrs med query-variabeln s=... i URL:en.

Här är ett exempel:
https://experiment.gizur.com/PressZero3.html?s=SV_0uo7HVkArefOwC2&d=999&c=1

Om ni inte vill lägga detta i embedded data kan ni helt enkelt hårdkoda det i URLen så här:

[https://experiment.gizur.com/PressZero3.html?s=](https://experiment.gizur.com/PressZero3.html?s=${e://Field/next_survey}&amp;c=${e://Field/cond}&amp;d=${e://Field/participantID)[SV_3ykeElPx20zls8K](https://samgu.eu.qualtrics.com/jfe/form/SV_3ykeElPx20zls8K)[&amp;c=${e://Field/cond}&amp;d=${e://Field/participantID](https://experiment.gizur.com/PressZero3.html?s=${e://Field/next_survey}&amp;c=${e://Field/cond}&amp;d=${e://Field/participantID)}

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by martinhed** [comment]
Ok skall träffa Patrik kl 3, kanske han förstår. Vad jag förstod på honom är det du som behöver ändra länken från din sida och att det inte är något som vi kan göra. Men jag återkommer

**Comment by colmsjo** [comment]
Jag har byggt det så det styrs från er sida (med query parametern s=).

Sent from ProtonMail for iOS

På tors, nov. 11, 2021 vid 13:21, martinhed ***@***.***> skrev:

**Comment by martinhed** [comment]
Tack, jag tror vi har fått det att funka nu

**Comment by colmsjo** [comment]
kanon!
